version: "3.9"
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tree_doctor
    ports:
      - "5432:5432"
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tree_doctor
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_POSTGIS=1
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS=minio
      - MINIO_SECRET=minio123
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"
  worker:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: rq worker analysis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tree_doctor
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_POSTGIS=1
    depends_on:
      - api
